environment:
  groups:
    - keys # This loads your GITHUB_TOKEN

workflows:
  ios-debug-build:
    name: iOS Debug Build
    instance_type: mac_mini_m2
    scripts:
      - name: Install Pods (with Secret Token)
        script: |
          cd mobile
          
          # This line tells the Mac to use your secret token for the private GoNative repo
          git config --global url."https://$GITHUB_TOKEN@github.com/".insteadOf "https://github.com/"
          git config --global url."https://$GITHUB_TOKEN@github.com/".insteadOf "git@github.com:"
          
          pod install
      - name: Build unsigned .ipa
        script: | 
          cd mobile
          xcodebuild build \
            -workspace "TRMMUSICPLAYER.xcworkspace" \
            -scheme "TRMMUSICPLAYER" \
            -configuration Debug \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""
      - name: Create IPA
        script: | 
          cd mobile
          mkdir -p build/ios/ipa/Payload
          cp -r $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/Debug-iphoneos/*.app build/ios/ipa/Payload
          cd build/ios/ipa && zip -r TRM_Player.ipa Payload
    artifacts:
      - mobile/build/ios/ipa/*.ipa