workflows:
  ios-debug-build:
    name: iOS Debug Build
    instance_type: mac_mini_m2
    scripts:
      - name: Fix Permissions and Build
        script: | 
          cd mobile
          # THIS IS THE FIX: Give execution permissions to all Pod scripts
          chmod -R +x Pods/Target\ Support\ Files/
          
          xcodebuild build \
            -workspace "TRMMUSICPLAYER.xcworkspace" \
            -scheme "TRMMUSICPLAYER" \
            -configuration Debug \
            -sdk iphoneos \
            -derivedDataPath "build" \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""
      - name: Create Unsigned IPA
        script: | 
          cd mobile
          mkdir -p build/ipa/Payload
          cp -r build/Build/Products/Debug-iphoneos/*.app build/ipa/Payload/
          cd build/ipa && zip -r TRM_Player.ipa Payload
    artifacts:
      - mobile/build/ipa/*.ipa