workflows:
  ios-debug-build:
    name: iOS Debug Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    scripts:
      - name: Install CocoaPods
        script: |
          # Step 1: Go into the mobile folder
          cd mobile
          
          # Step 2: Install the missing dependencies
          pod install
      - name: Build unsigned .ipa
        script: | 
          cd mobile
          
          # Use the .xcworkspace file now instead of .xcodeproj
          # CocoaPods creates a 'Workspace' which bundles your app + dependencies
          xcodebuild build \
            -workspace "TRMMUSICPLAYER.xcworkspace" \
            -scheme "TRMMUSICPLAYER" \
            -configuration Debug \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""
      - name: Create IPA
        script: | 
          cd mobile
          mkdir -p build/ios/ipa/Payload
          cp -r $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/Debug-iphoneos/*.app build/ios/ipa/Payload
          cd build/ios/ipa && zip -r TRM_Player.ipa Payload
    artifacts:
      - mobile/build/ios/ipa/*.ipa