workflows:
  ios-debug-build:
    name: iOS Debug Build
    instance_type: mac_mini_m2
    scripts:
      - name: Force Authentication
        script: |
          cd mobile
          # HARDCODED TOKEN - Bypasses the environment variable loading issue
          T="ghp_vYqoNTM9Bn2pi8AcLKfVA6jkR8Q50u38K4FK"
          
          git config --global url."https://x-access-token:${T}@github.com/".insteadOf "https://github.com/"
          git config --global url."https://x-access-token:${T}@github.com/".insteadOf "git@github.com:"
          
          pod repo add gonativeio-gonative-specs "https://x-access-token:${T}@github.com/gonativeio/gonative-specs.git" || true
          pod install
      - name: Build unsigned .ipa
        script: | 
          cd mobile
          xcodebuild build -workspace "TRMMUSICPLAYER.xcworkspace" -scheme "TRMMUSICPLAYER" -configuration Debug -sdk iphoneos CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=""
      - name: Create IPA
        script: | 
          cd mobile
          mkdir -p build/ios/ipa/Payload
          cp -r $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/Debug-iphoneos/*.app build/ios/ipa/Payload
          cd build/ios/ipa && zip -r TRM_Player.ipa Payload
    artifacts:
      - mobile/build/ios/ipa/*.ipa