workflows:
  ios-debug-build:
    name: iOS Debug Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    scripts:
      - name: Install CocoaPods
        script: |
          cd mobile
          
          # This line forces Git to use HTTPS instead of SSH for GoNative specs
          git config --global url."https://github.com/".insteadOf git@github.com:
          
          pod install
      - name: Build unsigned .ipa
        script: | 
          cd mobile
          xcodebuild build \
            -workspace "TRMMUSICPLAYER.xcworkspace" \
            -scheme "TRMMUSICPLAYER" \
            -configuration Debug \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""
      - name: Create IPA
        script: | 
          cd mobile
          mkdir -p build/ios/ipa/Payload
          cp -r $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/Debug-iphoneos/*.app build/ios/ipa/Payload
          cd build/ios/ipa && zip -r TRM_Player.ipa Payload
    artifacts:
      - mobile/build/ios/ipa/*.ipa