workflows:
  ios-debug-build:
    name: iOS Debug Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    scripts:
      - name: Build unsigned .ipa
        script: | 
          cd mobile
          
          # Step 1: Clean the build environment just in case
          xcodebuild clean -workspace "TRMMUSICPLAYER.xcworkspace" -scheme "TRMMUSICPLAYER"
          
          # Step 2: Build using the existing Pods folder
          xcodebuild build \
            -workspace "TRMMUSICPLAYER.xcworkspace" \
            -scheme "TRMMUSICPLAYER" \
            -configuration Debug \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""
      - name: Create IPA
        script: | 
          cd mobile
          mkdir -p build/ios/ipa/Payload
          # This copies the compiled app from the build folder
          cp -r $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/Debug-iphoneos/*.app build/ios/ipa/Payload
          cd build/ios/ipa && zip -r TRM_Player.ipa Payload
    artifacts:
      - mobile/build/ios/ipa/*.ipa