environment:
  groups:
    - keys # Make sure your GITHUB_TOKEN variable is in this group

workflows:
  ios-debug-build:
    name: iOS Debug Build
    instance_type: mac_mini_m2
    scripts:
      - name: Force Token Authentication
        script: |
          cd mobile
          
          # 1. Force Git to use your token for BOTH https and ssh requests
          git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
          git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "git@github.com:"
          
          # 2. Manually add the private repo using the token so CocoaPods doesn't have to 'guess'
          pod repo add gonativeio-gonative-specs "https://x-access-token:${GITHUB_TOKEN}@github.com/gonativeio/gonative-specs.git" || true
          
          # 3. Install
          pod install
      - name: Build unsigned .ipa
        script: | 
          cd mobile
          xcodebuild build \
            -workspace "TRMMUSICPLAYER.xcworkspace" \
            -scheme "TRMMUSICPLAYER" \
            -configuration Debug \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""
      - name: Create IPA
        script: | 
          cd mobile
          mkdir -p build/ios/ipa/Payload
          cp -r $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/Debug-iphoneos/*.app build/ios/ipa/Payload
          cd build/ios/ipa && zip -r TRM_Player.ipa Payload
    artifacts:
      - mobile/build/ios/ipa/*.ipa